### ISSUE TITLE
Not all fields are correctly updated

### ISSUE THREAD

**Issue by SubSide** [VSLCatena/AllUnitedToAD#3]
`cn` & `name` are not correctly updated.

There are a couple of users that were misspelled on creation. Those were later fixed but do not reflect on aforementioned fields.
This currently breaks name changes in for example Mensa as Mensa uses `cn`. (And I know `cn` might not be the correct field to use for Mensa)

**Comment by Kipjr** [comment]
cn = subset of dn (distinguishedname) 
`cn=kipjr, ou=users,dc=domain, dc=tld` , this needs to be unique just as `samaccountname` and `guid`. It is difficult to change this and I would recommend using `firstname` and `name` instead of `cn`

I will look into this.

**Comment by SubSide** [comment]
Although `name` isn't updated either, only `displayName` is.
And if `cn` can't easily be changed, then I think we shouldn't use peoples name for it

**Comment by Kipjr** [comment]
need to implement `Rename-ADObject` in `Function Set-Users`

**Comment by Kipjr** [comment]
Fixed with [7ea08d3](https://github.com/VSLCatena/AllUnitedToAD/commit/7ea08d3493dec594989428265982a74f140f6cb2)
